# Rename to ./config.toml or move to $HOME/.fattingo/config.toml
[server]
    address = ":5000"

## MYSQL DB - docker-compose
# [db]
#     type = "mysql"
#     user = "tommyblue"
#     password = "s3cr3t"
#     host = "db"
#     port = 3306
#     name = "fattingo"

## SQLITE DB
[db]
    type = "sqlite3"
    path = "./example-db.sqlite"
