name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: gofmt
        working-directory: backend
        run: make gofmt

      - name: govet
        working-directory: backend
        run: make govet

      - name: go mod verify
        working-directory: backend
        run: go mod verify

      - name: Test
        working-directory: backend
        run: make test

      - name: Build
        working-directory: backend
        run: make build
